### ISSUE TITLE
Feature request: animate frame

### ISSUE THREAD

**Issue by markuswinkler** [u10int/Kinetic#10]
.Frame would be a good to have animation target.
Not sure how concurrency is dealt with (e.g. .Frame in combination with .X).
Easiest solve could be that it is exclusive and has priority (and also stated in the docs).

**Comment by u10int** [comment]
For this use case you would just use both .Origin and .Size in a single tween which will be combined into a single frame animation under the hood.

**Comment by markuswinkler** [comment]
If the underlaying framework is already there can you please still implement it?
It would simplify the code a lot when you have to transition objects from one frame to match another, as it happens very often with custom transitions.
