### ISSUE TITLE
Feature Request: timeline.seekPercent (+possible Bug)

### ISSUE THREAD

**Issue by markuswinkler** [u10int/Kinetic#13]
It would be great if there is a seekPercent(percent:Double) method for timeline.
Background: I coupled a slider to a timeline and want to scrub the timeline back and forth.

I tried to implement it via an extension, works great, but the getter for percent threw me a curve ball because totalTime/time()/progress() returns total elapsed time instead of the time position inside the timeline. e.g. the totalDuration is 0.9 but I am getting values > 200 for totalTime

```
extension Timeline {
    func seekPercent(percent: Double) -> Timeline {
        self.percent = percent
        return self
    }

    var percent : Double {
        get {
            guard totalDuration > 0 else { return 1 }
            return totalTime / totalDuration
        }
        set(value) {
            var checkValue = value > 1 ? 1 : value
            checkValue = checkValue < 0 ? 0 : checkValue
            seek(checkValue * totalDuration)
        }
    }
}
```

**Comment by u10int** [comment]
This was kind of in there via the `progress()` method, which returns the playhead's current position from a value of 0 (beginning) to 1 (ending) which you can use to get the percentage. But there wasn't a way to set the position using the same method, so I just pushed up some additions and bug fixes that enables this.

I also added a position slider to the Timeline example in the demo app that demonstrates how this works. You essentially just use `progress()` to get the current position (e.g. updating the slider value) and `setProgress(progress: Float)` to move the animation's playhead to that position.

Note that just like TweenMax, I have both `progress()` and `totalProgress()` (and associated setter methods) which will result in different actions. You will typically always want to use `totalProgress()` and `setTotalProgress()` when a Tween or Timeline is set to repeat as these methods take repeat and repeatDelay into account. If an animation is not set to repeat, then `progress()` and `totalProgress()` will behave the same.

There are still a few minor bugs with resuming playback after calling `seek()` I'll be resolving over the next couple of days.

**Comment by markuswinkler** [comment]
Great! Works!
Is there a reason that progress is a Float instead of a Double?
(since Double is the default floating point type)
