### ISSUE TITLE
Bug: KeyPath doesn't set final value

### ISSUE THREAD

**Issue by markuswinkler** [u10int/Kinetic#14]
If easing is used then the final value is not set under certain conditions.
The example below should output 0 at the end but instead the 
output is -2.22044604925031e-16.

```
    var _testValue = 1.0
    var testValue : Double {
        get { return _testValue }
        set(value) {
            _testValue = value
            print(value)
        }
    }

override func viewDidAppear(animated: Bool) {
     Kinetic.to(self, duration: 0.3, options: [.KeyPath("testValue",0)]).ease(Easing.inOutSine).play()
}
```

**Comment by u10int** [comment]
Also just pushed up a fix for this issue which appeared to be related to floating point precision issues for certain easing formulas where it was never exactly the final value at a progress of 1.0. Not all easing methods had this issue, so I just added a check to ensure the returned value from `lerpFloat()` was always the `to` value for a time of 1.0.

**Comment by markuswinkler** [comment]
works! Thanks.
