### ISSUE TITLE
Feature request: .TintColor for TweenProperty

### ISSUE THREAD

**Issue by markuswinkler** [u10int/Kinetic#16]
would be nice to be able to tween the tintColor property of objects :)

**Comment by u10int** [comment]
Yeah I plan on adding support for other color properties soon, such as fillColor and borderColor for CALayer instances, so I'll throw tintColor in there as well. I'm considering refactoring the Property enum to a struct to reduce some of the complexity and duplication in the library with conditional checks on the Property enum values. Hopefully I can get that refactored next week when I have more free time to focus on it.

**Comment by markuswinkler** [comment]
Great! :+1:

**Comment by u10int** [comment]
Just pushed up support for fillColor and strokeColor on CAShapeLayer, and tintColor on UIView.

**Comment by markuswinkler** [comment]
Great, works! Thanks!
