### ISSUE TITLE
Bug: fromTo in a Timeline doesn't always set correct values if a time offset is used

### ISSUE THREAD

**Issue by markuswinkler** [u10int/Kinetic#18]
Following example

This is part of a complex timeline animation that reveals and hides elements:
`timeline.add(Kinetic.fromTo(square, duration: 0.2, from:[.Alpha(0), .Scale(0.9)], to:[.Alpha(1), .Scale(1), .Translate(0,0)]), position: 0.5)
`

If you animate the timeline via a slider and setTotalProgress(sliderValue) then the alpha sometimes gets stuck on a very light value when you slide back to 0. Happens on random.

**Comment by u10int** [comment]
@markuswinkler Just pushed up a fix for this on master if you want to give it a try and make sure it's working properly for you now as well.

**Comment by markuswinkler** [comment]
yes, seems to work. nice! :)
