### ISSUE TITLE
.Alpha sometimes doesn't fade in completely

### ISSUE THREAD

**Issue by markuswinkler** [u10int/Kinetic#2]
Fantastic engine! Feels like home coming from TweenMax. :+1: 

I noticed a small bug when using .Alpha. When I fade in a view with .Alpha the animation sometimes gets stuck just below 1, leaving the background slightly transparent. Happens totally on random.

**Comment by u10int** [comment]
Looks like sometimes the animation doesn't quite reach the final value depending on the refresh rate of the internal CADisplayLink. I'll make a change to always set the final value when a tween has completed which should correct this.

**Comment by markuswinkler** [comment]
Great, thanks!

**Comment by u10int** [comment]
Fixed in 0.9.0 I just pushed out.
