### ISSUE TITLE
Critical: order of parameters breaks execution

### ISSUE THREAD

**Issue by markuswinkler** [u10int/Kinetic#20]
I like the new syntax because it made it seem more expandable and also that the order of parameters doesn't matter. Unfortunately it does (and broke all my migrated code).
Is this an easy fix?

works:
`Kinetic.animate(square).to(.X(250)).duration(0.5).ease(Easing.inOutQuart).delay(1).play()`

doesn't work:
`Kinetic.animate(square).duration(0.5).to(.X(250)).ease(Easing.inOutQuart).delay(1).play()`

**Comment by u10int** [comment]
Looks like I missed that when refactoring the public API for the library, but the issue should be corrected in the updates I pushed out today.

**Comment by markuswinkler** [comment]
Works! Thanks!
