### ISSUE TITLE
Kinetic.set broken

### ISSUE THREAD

**Issue by markuswinkler** [u10int/Kinetic#21]
Kinetic.set stopped working.

doesn't work:
`Kinetic.set(self, props: .Rotate(0.25), .Scale(0.4))`

works:
`Kinetic.animate(self).duration(0).to(.Rotate(0.25), .Scale(0.4)).play()`

**Comment by markuswinkler** [comment]
changing the duration in the function call from 0 to 1 seems to fix it.

change:

```
public func set(target: NSObject, props: Property...) {
    let tween = Tween(target: target, from: nil, to: props, mode: .To)
    tween.duration(0)
    tween.seek(tween.duration)
}

public func setAll(targets: [NSObject], props: Property...) {
    for (_, item) in targets.enumerate() {
        let tween = Tween(target: item, from: nil, to: props, mode: .To)
        tween.duration(0)
        tween.seek(tween.duration)
    }
}
```

to:

```
public func set(target: NSObject, props: Property...) {
    let tween = Tween(target: target, from: nil, to: props, mode: .To)
    tween.duration(1)
    tween.seek(tween.duration)
}

public func setAll(targets: [NSObject], props: Property...) {
    for (_, item) in targets.enumerate() {
        let tween = Tween(target: item, from: nil, to: props, mode: .To)
        tween.duration(1)
        tween.seek(tween.duration)
    }
}
```

**Comment by u10int** [comment]
This issue has been corrected, so you don't need to set the duration to 1 anymore. The issue was that the `Kinetic.set` method wasn't `to()` with the desired properties before trying to seek to the end of its timeline, updating the properties. The preloader example makes extensive use of this method which is now working properly again.

**Comment by markuswinkler** [comment]
works! Thanks.
