### ISSUE TITLE
Bug: animateAll + stagger + delay is broken

### ISSUE THREAD

**Issue by markuswinkler** [u10int/Kinetic#22]
When I use animateAll + stagger + delay the last elements in the chain don't get fully animated. the smaller the stagger value, the sooner the animation stops. Removing delay displays the animations at the end in full as expected.

doesn't work (5 elements):
`Kinetic.animateAll(elements).from(.ScaleXY(0,0)).to(.ScaleXY(0.9,0.9)).duration(0.4).stagger(0.08).delay(0.3).play()`

works (5 elements):
`Kinetic.animateAll(elements).from(.ScaleXY(0,0)).to(.ScaleXY(0.9,0.9)).duration(0.4).stagger(0.08).play()`

**Comment by u10int** [comment]
Thanks, issue should be fixed now. Looks like I wasn't accounting for a timeline's delay value when determining if a timeline had completed.

**Comment by markuswinkler** [comment]
Works! Thanks for the quick solve!
