### ISSUE TITLE
Please add @discardableResult to key functions in the swift 3 branch

### ISSUE THREAD

**Issue by markuswinkler** [u10int/Kinetic#26]
Please add @discardableResult (at least) to key functions (play/onComplete/onUpdate/setTotalProgress/...) to suppress the compiler warning.

thank you! :)

**Comment by u10int** [comment]
This has been added to the necessary methods in the latest swift-3 branch.

**Comment by markuswinkler** [comment]
Thank you for keeping it in such great shape!
