### ISSUE TITLE
Feature Request: Swift 3

### ISSUE THREAD

**Issue by smileypop** [u10int/Kinetic#27]
I see the Swift 3 update is underway. Any luck get the pod to build properly?

I'd love to use this framework in my project. Thanks!

**Comment by u10int** [comment]
Sorry, I've been focused on the library refactoring and improvements in my props-refactor branch where I've already converted to Swift 3 that I forgot to come back to updating master. I knocked that out this morning and pushed out 0.9.5 and updated the pod so the library now supports Swift 3.

**Comment by smileypop** [comment]
I got it working in my project. Thanks for the update!
