### ISSUE TITLE
.Center(xVal, yVal) doesn't exist

### ISSUE THREAD

**Issue by markuswinkler** [u10int/Kinetic#3]
.Center(xVal, yVal) property doesn't exist in public enum Property
(despite documentation)

**Comment by u10int** [comment]
Thanks for the catch, looks like I forgot to come back and add that in after writing that part of the docs. I'll get that in the 0.9.0 release today with fixes for your other two issues.

**Comment by markuswinkler** [comment]
Great! 👍

**Comment by u10int** [comment]
Fixed in 0.9.0 I just pushed out.
