### ISSUE TITLE
Memory leak in Tween

### ISSUE THREAD

**Issue by mystikxkemix** [u10int/Kinetic#31]
You have a memory leak in your Tween module. It impacts TweenObjects and TransformProperties
![image](https://user-images.githubusercontent.com/9988890/28458780-408234d8-6e0b-11e7-9ce6-c123d30bef74.png)

**Comment by u10int** [comment]
@mystikxkemix Can you provide more details and/or context about this leak you're seeing? Is this using the demo or within your own code? I just tested via the demo project and not seeing the same type of closure-related leak.

**Comment by mystikxkemix** [comment]
My bad, that was a leak in my program
