### ISSUE TITLE
UIViews inside ScrollView animated

### ISSUE THREAD

**Issue by netgfx** [u10int/Kinetic#36]
I have some UIViews inside a single ScrollView, but after they animate their `y` via `Shift(y: somevalue)` value and become larger than the ScrollView height, the scrollview doesn't scroll. Do I need to animate a specific `y` property? or update something?

**Comment by u10int** [comment]
You would need to manage the scroll view's contentHeight and contentOffset properties within your own code based on the current position of the view you're shifting. You could do this within the `tween.on(.updated)` callback block on you tween while the animation is running.
