### ISSUE TITLE
Can we tween a tableview?

### ISSUE THREAD

**Issue by netgfx** [u10int/Kinetic#37]
Trying to tween a UITableView from bottom (set with PinLayout) to top of screen or even a set amount of y (100 or so) but it doesn't animate at all. The `onComplete` fires successfully after the duration.

Any ideas why this wouldn't work?

**Comment by u10int** [comment]
Are you trying to animate the UITableView itself, or animate the cells when they're shown on screen? Can you provide some code where you're applying the animation?

**Comment by netgfx** [comment]
I was trying to animate the TableView `y` but Shift did the trick, having a bit of a problem with Size increasing the width of the table view but I'll figure it out.
