### ISSUE TITLE
EasingType - Bounce? How to use this?

### ISSUE THREAD

**Issue by Saravana-swengineer** [u10int/Kinetic#39]
Hi @u10int ,

How would you animate an object using easing like bounce, elastic and custom related eases in GreenSock?

Thanks for this animation library!

Thanks,
Saravana

**Comment by u10int** [comment]
You would just need to use the `.ease(_ easing: Easing.EasingType)` method on your animation/tween instance. The supported easing functions currently supported are listed here: https://github.com/u10int/Kinetic/blob/master/Pod/Classes/Easing.swift#L40

Unfortunately there isn't support for bounce or elastic, but you can use your own curve using the `.custom()` type and providing your four custom control points. I'll look at adding support for bounce and elastic soon as those will be nice to have.

**Comment by Saravana-swengineer** [comment]
Thanks for your response,

Kindly let me know how to use **.custom()** type for bounce options.

**Comment by u10int** [comment]
@Saravana-iOS Just wanted to let you know I was able to wrap up the necessary refactoring for the easing timing functions and got bounce and elastic easing supported. The pod for the project has also been updated to 1.1.0: https://github.com/u10int/Kinetic/releases/tag/1.1.0

So you can now do: `ease(Bounce.easeOut)` (or `Bounce.easeIn`, `Bounce.easeInOut`)

Let me know if you have any issues with the new release.

Thanks!
