### ISSUE TITLE
Feature request: "delay" for timeline add

### ISSUE THREAD

**Issue by markuswinkler** [u10int/Kinetic#9]
Add delay as a parameter for timeline adds (like position).
This opens the door to specify a negative delay, to start the animation before the previous one has ended. This kind of slight overlap (e.g. -0.2) is often the difference for an animation sequence between "ok" and "wow"

**Delay parameter**
instead of writing

```
anim.add(Kinetic.to(square, duration: 0.2, options: [ .Rotate(-1) ]).ease(Easing.outSine))
anim.add(Kinetic.to(square, duration: 0.4, options: [ .Rotate(1) ]).ease(Easing.inOutSine).delay(1))
anim.add(Kinetic.to(square, duration: 0.2, options: [ .Rotate(0) ]).ease(Easing.outSine))
```

you could also write

```
anim.add(Kinetic.to(square, duration: 0.2, options: [ .Rotate(-1) ]).ease(Easing.outSine))
anim.add(Kinetic.to(square, duration: 0.4, options: [ .Rotate(1) ]).ease(Easing.inOutSine), delay: 1)
anim.add(Kinetic.to(square, duration: 0.2, options: [ .Rotate(0) ]).ease(Easing.outSine))
```

but it shouldn't break

```
anim.add(Kinetic.to(square, duration: 0.2, options: [ .Rotate(-1) ]).ease(Easing.outSine))
anim.add(Kinetic.to(square, duration: 0.4, options: [ .Rotate(1) ]).ease(Easing.inOutSine).delay(0.5), delay: 0.5)
anim.add(Kinetic.to(square, duration: 0.2, options: [ .Rotate(0) ]).ease(Easing.outSine))
```

**Negative delay parameter**

```
anim.add(Kinetic.to(square, duration: 1, options: [ .Rotate(-1) ]).ease(Easing.outSine))
anim.add(Kinetic.to(square, duration: 0.3, options: [ .Alpha(0) ]), delay: -0.3)
```

**Comment by u10int** [comment]
You can already adjust where along the timeline a tween is added by using the `add(value:position:)` method on Timeline, where the value for `position` can be a specific time value (in seconds) along the timeline or a string value relative to the current end of the timeline or relative to a pre-defined label position. This works very much the same as it would with TimelineMax.

So for your example, the following would achieve the same effect:

Positive offset:

```
let timeline = Timeline()
timeline.add(Kinetic.to(square, duration: 0.2, options: [ .Rotate(-1) ]).ease(Easing.outSine))
timeline.add(Kinetic.to(square, duration: 0.4, options: [ .Rotate(1) ]).ease(Easing.inOutSine), position: "+=1")
timeline.add(Kinetic.to(square, duration: 0.2, options: [ .Rotate(0) ]).ease(Easing.outSine))
```

Negative offset:

```
let timeline = Timeline()
timeline.add(Kinetic.to(square, duration: 1, options: [ .Rotate(-1) ]).ease(Easing.outSine))
timeline.add(Kinetic.to(square, duration: 0.3, options: [ .Alpha(0) ]), position: "-=3")
```

Label offset 

```
let timeline = Timeline()
timeline.addLabel("rotateBack", position: 1.5)
timeline.add(Kinetic.to(square, duration: 0.2, options: [ .Rotate(-1) ]).ease(Easing.outSine))
timeline.add(Kinetic.to(square, duration: 0.4, options: [ .Rotate(1) ]).ease(Easing.inOutSine), position: "rotateBack+=1")
timeline.add(Kinetic.to(square, duration: 0.2, options: [ .Rotate(0) ]).ease(Easing.outSine))
```

**Comment by markuswinkler** [comment]
Sounds good! I just tested that but can't get it working.

```
let timeline = Timeline()
timeline.add(Kinetic.to(square, duration: 1.2, options: [ .Rotate(-1) ]).ease(Easing.outSine))
timeline.add(Kinetic.to(square, duration: 1.4, options: [ .Rotate(1) ]).ease(Easing.inOutSine).delay(1))
timeline.add(Kinetic.to(square, duration: 1.2, options: [ .Rotate(0) ]).ease(Easing.outSine))
timeline.add(Kinetic.to(square, duration: 1.2, options: [ .Scale(0.7) ]).ease(Easing.outSine),position:"-=1.2")
```

This should scale the square at the last animation, but it only blinks in the beginning.

**Comment by u10int** [comment]
I wasn't able to reproduce the blinking you mentioned, but it's definitely not working as expected (though the position offset was working fine). Running through the code last evening I noticed there are definitely some issues dealing with layer transforms and combing them since working with CATransform3D can be a struggle at times, so my plan is to spend some time fixing a lot of those.

**Comment by markuswinkler** [comment]
Seems like I have a knack for finding the worst examples ;)
:+1: Looking forward to the solve
